### ISSUE TITLE
ある文字種を「含めない」指定がしにくい

### ISSUE THREAD

**Issue by amderbar** [amderbar/mkpasswdpwa#4]
ある文字種の指定文字数に`0`を入れたとしても、その数値はパスワードに含めるべき「最低文字数」であって、その文字を「含めない」という意味にはならない。

他文字種の指定文字数の和を長さと同じにしてしまえば`0`を指定した文字種は含まれなくなるが、それはそれでよくない。なんとかしたい。
* 他文字種が含まれる文字数が完全に指定されている
* そもそも指定の仕方がめんどい。直感的でない

**Comment by koheisakata** [comment]
記号文字に関しては、Ascii記号内でも使用できるものが制限されている場合があります。
文字ごとに使用・不使用を指定できないと、こういう場合に対処できないと思われます。

e.g. とある会計システムのログインパスワードで使用可能な記号は以下。クォート系やカンマが含まれていない。
`+ - / * # & % $ @ . ~`

**Comment by amderbar** [comment]
@koheisakata ご報告ありがとうございます。併せて対応します。

**Comment by amderbar** [comment]
とりあえず、以下の機能を実現できました。
1. 半角英数記号の各文字種ごとに使う使わないを選べる
2. 記号は文字ごとに使う使わないを選べる

UIがイケてないのは別issueとします…。
